#!/usr/bin/env bash
#returns all subdomains records and ips for a domain

domain=$1
function printing {
    for var in "$@"
    do
            full_domain=$var.$1
            dig "$full_domain" |\
            awk -v var=$var '/ANSWER SECTION:/ {getline; print "The subdomain " var " is a " $4 " record and points to " $5}'
    done
}
if [ $# == 1 ]; then
    printing "$domain" www lb-01 web-01 web-02 
elif [ $# == 2 ]; then
    subdomain=$2
    printing "$domain" "$subdomain"
fi
