#!/usr/bin/env bash
#returns all subdomains records and ips for a domain

domain=$1
function printing {
    for var in "$@"
    do
            full_domain=$var.$5
            dig $full_domain |\
            grep -e "^$var" |\
            awk -vvar=$var '\
            {print "The subdomain " var " is a " $4 " record and points to " $5}'
    done
}
printing www lb-01 web-01 web-02 $domain
