#!/usr/bin/env bash
# install ngix, setup it up on port 80 HTTP and write Holberton School in index file
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.html
sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/server_name _;/ a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
service nginx restart
