#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
#Your script should only display:
#	username
#	user id
#	Home directory path for the user
#Requirements:
#	You must use the while loop (for and until are forbidden)

input="text_messages.log"
while IFS= read -r line
do
  ./100-textme.rb "$line"
done  < "$input"
