#!/usr/bin/env bash
# install ngix, setup it up on port 80 HTTP 
# and write Holberton School in index file
# add a custom header with hostname as value
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}"
service nginx restart
