#!/usr/bin/env bash
#Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009

ps -H -Ao user,pid,%cpu,%mem,vsz,rss,tname,stat,bsdstart,time,command | grep bash