#!/usr/bin/env bash
# Bash script that displays:

#    To infinity and beyond indefinitely
#    With a sleep 2 in between each iteration
#    I am invincible!!! when receiving a SIGTERM signal

#Make a copy of your 6-kill_me_now_made_easy script,
#name it 67-kill_me_now_made_easy, that kills the 7
#highlander process instead of the 4-to_infinity_and_beyond one.

trap "echo I am invincible!!!" SIGTERM
while true; do
        echo "To infinity and beyond"
        sleep 2
done
