#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100.
# Requirements:
#	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number
#	In a list format

for i in {1..100}; do
	let "m_three = $i % 3"
	let "m_five = $i % 5"
	if [ $m_three -eq 0  ] && [ $m_five -eq 0 ]; then
		echo FizzBuzz
	elif [ $m_three -eq 0 ]; then
		echo Fizz
	elif [ $m_five -eq 0 ]; then
		echo Buzz
	else
		echo "$i"
	fi;
done
