#!/usr/bin/env bash
#fixing server not able to start and put it to listen to 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
